services:
  - type: web
    name: fimbot
    env: python
    region: singapore
    buildCommand: |
      python -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      gunicorn bot_logic:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PATH
        value: /opt/render/project/src/venv/bin:/opt/render/project/src:${PATH}
    autoDeploy: true

