services:
  - type: web
    name: fimbot
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot_logic:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
    autoDeploy: true

