services:
- type: web
  name: fimbot
  env: python
  region: singapore
  buildCommand: |
    # Install ncurses and set up non-interactive environment
    export DEBIAN_FRONTEND=noninteractive
    apt-get update && apt-get install -y ncurses-bin
    # Create virtual environment
    python -m venv /opt/venv
    . /opt/venv/bin/activate
    # Install Python dependencies
    pip install --upgrade pip
    pip install -r requirements.txt
  startCommand: |
    . /opt/venv/bin/activate
    gunicorn bot_logic:app --workers 4 --threads 2 --timeout 120 --bind 0.0.0.0:$PORT
  envVars:
    - key: PYTHON_VERSION
      value: 3.8.0
    - key: PYTHONPATH
      value: /opt/venv/lib/python3.8/site-packages
    - key: PATH
      value: /opt/venv/bin:/usr/bin:$PATH
    - key: TERM
      value: xterm-256color
    - key: DEBIAN_FRONTEND
      value: noninteractive
    - key: NO_COLOR
      value: "1"  # Disable color output if colors are causing issues
  healthCheckPath: /health
  autoDeploy: true

